ctrl_interface=/var/run/wpa_supplicant
update_config=1
dik_cipher=0
dik=40C7BC7214FEFB8E65F3FB0F097F4A79

network={
	ssid="Wi-Fi_70"
	key_mgmt=WPA-EAP-SHA256
	eap=TLS
	pairwise=GCMP-256
	group=CCMP
	identity="user-p256"
	ca_cert="/tmp/wfa/certs/cas.pem"
	client_cert="/tmp/wfa/certs/user-p256.pem"
	private_key="/tmp/wfa/certs/user-p256.pem"
	private_key_passwd="wifi"
	ieee80211w=1
	beacon_prot=1
}
