ctrl_interface=/var/run/wpa_supplicant
update_config=1
dik_cipher=0
dik=40C7BC7214FEFB8E65F3FB0F097F4A79

network={
	ssid="Wi-Fi_330"
	sae_password="12345678"
	key_mgmt=SAE-EXT-KEY
	pairwise=GCMP-256
	group=CCMP
	ieee80211w=2
	rsn_overriding=1
}
