ctrl_interface=/var/run/wpa_supplicant
update_config=1
dik_cipher=0
dik=34B10441A6DAC6451DA13FBC9EE022AA

network={
	ssid="Wi-Fi_400"
	key_mgmt=WPA-EAP-SHA256
	eap=TLS
	identity="user-p256"
	ca_cert="/tmp/wfa/certs/cas.pem"
	client_cert="/tmp/wfa/certs/user-p256.pem"
	private_key="/tmp/wfa/certs/user-p256.pem"
    ieee80211w=1
}

