ctrl_interface=/var/run/wpa_supplicant
update_config=1
dik_cipher=0
dik=5877771E19FF6E59F3F0A8ADD60CC1CB
mld_connect_band_pref=2
#mld_connect_bssid_pref=00:03:7f:04:30:82

network={
    ssid="Wi-Fi_7_250"
    key_mgmt=SAE-EXT-KEY EPPKE
    pairwise=GCMP-256
    group=CCMP
    ieee80211w=1
    sae_password="12345678"
    sae_pwe=2
    pmksa_privacy=1
}
